server:
  port: 8002

spring:
  application:
    name: stock-service
  cloud:
    config:
      name: stock-service
  config:
    import: optional:configserver:http://127.0.0.1:8888

eureka:
  client:
    eureka:
    register-with-eureka: true
    fetch-registry:  true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
