server:
  port: 8001

spring:
  application:
    name: order-service

  # cofing service 설정
  cloud:
    config:
      name: order-service
  config:
    import: optional:configserver:http://127.0.0.1:8888 # Config Server 주소

eureka:
  client:
    register-with-eureka: true
    fetch-registry:  true
    # 통신할 Erueka Server(discovery-service) 의 위치를 지정하고
    # Eurea Server에 이 Eureka Client를 등록
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
