server:
  port: 8001

spring:
  application:
    name: order-service

  # cofing service 설정
  cloud:
    config:
      name: order-service
  config:
    import: optional:configserver:http://127.0.0.1:8888 # Config Server 주소

  # rabbitmq 설정 (config 자동 업데이트를 위해)
  # Spring Cloud Bus
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

# actuator 를 이용하기 위해 endpoint의 busrefresh 열기
management:
  endpoints:
    web:
      exposure:
        include: busrefresh

eureka:
  client:
    register-with-eureka: true
    fetch-registry:  true
    # 통신할 Erueka Server(discovery-service) 의 위치를 지정하고
    # Eurea Server에 이 Eureka Client를 등록
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
