server:
  port: 8001

spring:
  application:
    name: order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry:  true
    # 통신할 Erueka Server(discovery-service) 의 위치를 지정하고
    # Eurea Server에 이 Eureka Client를 등록
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
