server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        encrypt.enabled: true
        git:
          uri: https://github.com/cso6005/SpringCloud-config
          #username:
          #password:

